### ISSUE TITLE
Some thoughts on hiding relevance of Std Dev

### ISSUE THREAD

**Issue by steven5clu884** [reesporte/bugfruit#1]
This is not an issue so much as my thoughts as an applied mathematician, and Intel Device Driver tester for several years out of Folsom, CA.  
You may find that it would be more descriptive to provide % std Dev instead of the actual Std Dev.
So for the Table benchmarks/bench-x-small.log

% Std Dev = 100* std Dev/Arithmetic Mean Average is what I believe you mean by Average

Type | Average ops/sec | % Std. Dev. ops/sec
-- | -- | --
Set | 417,070 | 1.9 
Delete | 583,134 | 1.25
Get | 7,891,966 | 2.66

Now you can immediately see that the std dev for Get is TWICE that of Delete and Set and perhaps lead you to ask the question why ??  What is going on with Get  that the Std Dev is twice as wide for Get than for Set and Delete

For your 10,000,000 iteration test
benchmarks/bench-small.log

Type | Average ops/sec | % Std. Dev. ops/sec
-- | -- | --
Set | 360,777 | 0.86
Delete | 466,481 | 0.89
Get | 6,171,403 | 2.82

Notice the decrease in the % Std Dev for Set and Delete WHILE THE Get % std dev DID NOT DECREASE at all
This is an immediate red flag that should be investigated

This is your reputation that is on the line, so I suggest you investigate the 2 tables benchmarks/bench-large.log as well I think they follow a similar pattern.
My best wishes to you and your loved ones

**Comment by reesporte** [comment]
Hey @steven5clu884, thanks for your comment! I appreciate you taking the time to give me some feedback. 

You mention that "the std dev for Get is TWICE that of Delete and Set" in the smaller benchmark. You also note that there is a decrease in the standard deviation in the same benchmark with a larger number of _operations_ (`bench-small`). You claim this is a "red flag". 

I think your claim that this is a red flag may be based in a misunderstanding. Namely, that `bench-small` is an identical benchmark to `bench-x-small` but with more iterations. This is not the case. `bench-small` runs the same number of iterations as `bench-x-small`. The number of _operations per iteration_ increases from 1,000,000 in `bench-x-small` to 10,000,000 in `bench-small`. These are ultimately different benchmarks, highlighting the performance of the database under different loads. `bench-small` is benchmarking the performance of 10,000,000 sets, gets, and deletes, while `bench-x-small` is benchmarking the performance of 1,000,000 sets, gets, and deletes.  Given that these are independent experiments, I feel comfortable with their different coefficients of variation.

This brings me to my next point. If the goal were to compare between benchmarks for the same operations, that were identical in all ways except for sample size, using the coefficient of variation could facilitate this comparison between like operations. However, given that `bench-small` and `bench-x-small` benchmark differ in operation load, and not in sample size, I don't think it works for this case. 

Thanks again for your comment! Please let me know if you have any other feedback / suggestions.
